import { CertificateLayout } from "./types";

export interface TemplatePreset {
  id: string;
  name: string;
  description: string;
  layout: CertificateLayout;
}

export const PRESET_TEMPLATES: TemplatePreset[] = [
  {
    id: "classic-gold",
    name: "Classic Gold Executive",
    description: "Traditional elegant certificate layout with gold borders, formal typography, and signature fields.",
    layout: {
      width: 1000,
      height: 700,
      backgroundColor: "#FFFFFF",
      borderColor: "#D97706",
      borderWidth: 10,
      showFrame: true,
      frameStyle: "classic",
      elements: [
        {
          id: "el-title",
          type: "title",
          label: "Certificate Title",
          text: "CERTIFICATE OF ACHIEVEMENT",
          x: 50,
          y: 18,
          fontSize: 32,
          fontFamily: "Cinzel, Times New Roman, serif",
          fontStyle: "bold",
          color: "#0F172A",
          align: "center",
          visible: true,
        },
        {
          id: "el-subtitle",
          type: "subtitle",
          label: "Sub-Title",
          text: "PROUDLY PRESENTED TO",
          x: 50,
          y: 28,
          fontSize: 14,
          fontFamily: "Inter, sans-serif",
          fontStyle: "bold",
          color: "#D97706",
          align: "center",
          visible: true,
        },
        {
          id: "el-name",
          type: "name",
          label: "Participant Name Field",
          text: "{{name}}",
          x: 50,
          y: 40,
          fontSize: 42,
          fontFamily: "Playfair Display, Georgia, serif",
          fontStyle: "bold",
          color: "#1E3A8A",
          align: "center",
          visible: true,
        },
        {
          id: "el-customText",
          type: "customText",
          label: "Custom Body Text",
          text: "For outstanding performance, dedication, and technical excellence in the",
          x: 50,
          y: 52,
          fontSize: 16,
          fontFamily: "Inter, sans-serif",
          fontStyle: "normal",
          color: "#475569",
          align: "center",
          visible: true,
        },
        {
          id: "el-eventName",
          type: "eventName",
          label: "Event / Hackathon Name",
          text: "{{eventName}}",
          x: 50,
          y: 60,
          fontSize: 22,
          fontFamily: "Inter, sans-serif",
          fontStyle: "bold",
          color: "#2563EB",
          align: "center",
          visible: true,
        },
        {
          id: "el-date",
          type: "date",
          label: "Issue Date",
          text: "Issued on: {{date}}",
          x: 25,
          y: 80,
          fontSize: 14,
          fontFamily: "Inter, sans-serif",
          fontStyle: "normal",
          color: "#64748B",
          align: "center",
          visible: true,
        },
        {
          id: "el-uniqueId",
          type: "uniqueId",
          label: "Verification ID Field",
          text: "{{uniqueId}}",
          x: 25,
          y: 86,
          fontSize: 13,
          fontFamily: "Courier New, monospace",
          fontStyle: "bold",
          color: "#2563EB",
          align: "center",
          visible: true,
        },
        {
          id: "el-qrCode",
          type: "qrCode",
          label: "QR Code Field",
          text: "",
          x: 78,
          y: 75,
          fontSize: 14,
          fontFamily: "Inter",
          color: "#0F172A",
          align: "center",
          width: 90,
          height: 90,
          visible: true,
        },
      ],
    },
  },
  {
    id: "modern-minimal",
    name: "Modern Minimalist",
    description: "Clean, crisp modern aesthetic with bold blue typography and spacious layout.",
    layout: {
      width: 1000,
      height: 700,
      backgroundColor: "#F8FAFC",
      borderColor: "#2563EB",
      borderWidth: 6,
      showFrame: true,
      frameStyle: "modern",
      elements: [
        {
          id: "el-title",
          type: "title",
          label: "Certificate Title",
          text: "CERTIFICATE OF EXCELLENCE",
          x: 50,
          y: 20,
          fontSize: 34,
          fontFamily: "Outfit, Inter, sans-serif",
          fontStyle: "bold",
          color: "#2563EB",
          align: "center",
          visible: true,
        },
        {
          id: "el-subtitle",
          type: "subtitle",
          label: "Sub-Title",
          text: "THIS IS TO CERTIFY THAT",
          x: 50,
          y: 30,
          fontSize: 13,
          fontFamily: "Inter, sans-serif",
          fontStyle: "bold",
          color: "#64748B",
          align: "center",
          visible: true,
        },
        {
          id: "el-name",
          type: "name",
          label: "Participant Name Field",
          text: "{{name}}",
          x: 50,
          y: 42,
          fontSize: 44,
          fontFamily: "Outfit, sans-serif",
          fontStyle: "bold",
          color: "#0F172A",
          align: "center",
          visible: true,
        },
        {
          id: "el-eventName",
          type: "eventName",
          label: "Event / Hackathon Name",
          text: "{{eventName}}",
          x: 50,
          y: 56,
          fontSize: 20,
          fontFamily: "Inter, sans-serif",
          fontStyle: "bold",
          color: "#06B6D4",
          align: "center",
          visible: true,
        },
        {
          id: "el-date",
          type: "date",
          label: "Issue Date",
          text: "{{date}}",
          x: 20,
          y: 82,
          fontSize: 13,
          fontFamily: "Inter, sans-serif",
          fontStyle: "normal",
          color: "#475569",
          align: "center",
          visible: true,
        },
        {
          id: "el-uniqueId",
          type: "uniqueId",
          label: "Verification ID Field",
          text: "{{uniqueId}}",
          x: 50,
          y: 84,
          fontSize: 14,
          fontFamily: "Courier New, monospace",
          fontStyle: "bold",
          color: "#2563EB",
          align: "center",
          visible: true,
        },
        {
          id: "el-qrCode",
          type: "qrCode",
          label: "QR Code Field",
          text: "",
          x: 82,
          y: 74,
          fontSize: 14,
          fontFamily: "Inter",
          color: "#0F172A",
          align: "center",
          width: 85,
          height: 85,
          visible: true,
        },
      ],
    },
  },
  {
    id: "cyberpunk-dark",
    name: "Cyberpunk Arena Dark",
    description: "Sleek dark theme with neon cyan and pink accents tailored for developer hackathons.",
    layout: {
      width: 1000,
      height: 700,
      backgroundColor: "#0F172A",
      borderColor: "#06B6D4",
      borderWidth: 8,
      showFrame: true,
      frameStyle: "dark",
      elements: [
        {
          id: "el-title",
          type: "title",
          label: "Certificate Title",
          text: "FRONTEND ARENA CERTIFICATE",
          x: 50,
          y: 18,
          fontSize: 30,
          fontFamily: "Outfit, Inter, sans-serif",
          fontStyle: "bold",
          color: "#06B6D4",
          align: "center",
          visible: true,
        },
        {
          id: "el-subtitle",
          type: "subtitle",
          label: "Sub-Title",
          text: "OFFICIAL PARTICIPATION & ACHIEVEMENT CREDENTIAL",
          x: 50,
          y: 27,
          fontSize: 12,
          fontFamily: "Inter, sans-serif",
          fontStyle: "bold",
          color: "#FF006E",
          align: "center",
          visible: true,
        },
        {
          id: "el-name",
          type: "name",
          label: "Participant Name Field",
          text: "{{name}}",
          x: 50,
          y: 40,
          fontSize: 42,
          fontFamily: "Outfit, sans-serif",
          fontStyle: "bold",
          color: "#FFFFFF",
          align: "center",
          visible: true,
        },
        {
          id: "el-customText",
          type: "customText",
          label: "Custom Body Text",
          text: "Has successfully submitted code and completed automated judging for",
          x: 50,
          y: 52,
          fontSize: 15,
          fontFamily: "Inter, sans-serif",
          fontStyle: "normal",
          color: "#94A3B8",
          align: "center",
          visible: true,
        },
        {
          id: "el-eventName",
          type: "eventName",
          label: "Event / Hackathon Name",
          text: "{{eventName}}",
          x: 50,
          y: 60,
          fontSize: 22,
          fontFamily: "Outfit, sans-serif",
          fontStyle: "bold",
          color: "#38BDF8",
          align: "center",
          visible: true,
        },
        {
          id: "el-uniqueId",
          type: "uniqueId",
          label: "Verification ID Field",
          text: "{{uniqueId}}",
          x: 25,
          y: 82,
          fontSize: 14,
          fontFamily: "Courier New, monospace",
          fontStyle: "bold",
          color: "#06B6D4",
          align: "center",
          visible: true,
        },
        {
          id: "el-date",
          type: "date",
          label: "Issue Date",
          text: "Date: {{date}}",
          x: 25,
          y: 88,
          fontSize: 12,
          fontFamily: "Inter, sans-serif",
          fontStyle: "normal",
          color: "#94A3B8",
          align: "center",
          visible: true,
        },
        {
          id: "el-qrCode",
          type: "qrCode",
          label: "QR Code Field",
          text: "",
          x: 80,
          y: 74,
          fontSize: 14,
          fontFamily: "Inter",
          color: "#FFFFFF",
          align: "center",
          width: 90,
          height: 90,
          visible: true,
        },
      ],
    },
  },
];
