import { CertificateLayout } from "./types";

export interface TemplatePreset {
  id: string;
  name: string;
  description: string;
  layout: CertificateLayout;
}

export const DEFAULT_OVERLAY_ELEMENTS = [
  {
    id: "el-title",
    type: "title" as const,
    label: "Certificate Title",
    text: "CERTIFICATE OF EXCELLENCE",
    x: 50,
    y: 18,
    fontSize: 34,
    fontFamily: "Outfit, Inter, sans-serif",
    fontStyle: "bold" as const,
    color: "#2563EB",
    align: "center" as const,
    visible: true,
    zIndex: 1,
  },
  {
    id: "el-subtitle",
    type: "subtitle" as const,
    label: "Certificate Label",
    text: "THIS IS TO CERTIFY THAT",
    x: 50,
    y: 28,
    fontSize: 13,
    fontFamily: "Inter, sans-serif",
    fontStyle: "bold" as const,
    color: "#64748B",
    align: "center" as const,
    visible: true,
    zIndex: 2,
  },
  {
    id: "el-name",
    type: "name" as const,
    label: "Participant Name",
    text: "{{name}}",
    x: 50,
    y: 42,
    fontSize: 44,
    fontFamily: "Playfair Display, Georgia, serif",
    fontStyle: "bold" as const,
    color: "#0F172A",
    align: "center" as const,
    visible: true,
    zIndex: 3,
  },
  {
    id: "el-customText",
    type: "customText" as const,
    label: "Custom Description",
    text: "For outstanding performance, dedication, and technical excellence in",
    x: 50,
    y: 52,
    fontSize: 15,
    fontFamily: "Inter, sans-serif",
    fontStyle: "normal" as const,
    color: "#475569",
    align: "center" as const,
    visible: true,
    zIndex: 4,
  },
  {
    id: "el-eventName",
    type: "eventName" as const,
    label: "Event Name",
    text: "{{eventName}}",
    x: 50,
    y: 60,
    fontSize: 22,
    fontFamily: "Outfit, sans-serif",
    fontStyle: "bold" as const,
    color: "#2563EB",
    align: "center" as const,
    visible: true,
    zIndex: 5,
  },
  {
    id: "el-date",
    type: "date" as const,
    label: "Issue Date",
    text: "Issued on: {{date}}",
    x: 25,
    y: 82,
    fontSize: 13,
    fontFamily: "Inter, sans-serif",
    fontStyle: "normal" as const,
    color: "#64748B",
    align: "center" as const,
    visible: true,
    zIndex: 6,
  },
  {
    id: "el-uniqueId",
    type: "uniqueId" as const,
    label: "Verification ID",
    text: "ID: {{uniqueId}}",
    x: 25,
    y: 88,
    fontSize: 13,
    fontFamily: "Courier New, monospace",
    fontStyle: "bold" as const,
    color: "#2563EB",
    align: "center" as const,
    visible: true,
    zIndex: 7,
  },
  {
    id: "el-qrCode",
    type: "qrCode" as const,
    label: "QR Code",
    text: "",
    x: 82,
    y: 76,
    fontSize: 14,
    fontFamily: "Inter",
    color: "#0F172A",
    align: "center" as const,
    width: 90,
    height: 90,
    visible: true,
    zIndex: 8,
  },
];

export const PRESET_TEMPLATES: TemplatePreset[] = [
  {
    id: "modern-minimal",
    name: "Modern Minimalist",
    description: "Clean, crisp modern aesthetic with bold blue typography and spacious layout.",
    layout: {
      width: 1000,
      height: 700,
      backgroundColor: "#F8FAFC",
      borderColor: "#2563EB",
      borderWidth: 6,
      showFrame: true,
      frameStyle: "modern",
      elements: DEFAULT_OVERLAY_ELEMENTS,
    },
  },
  {
    id: "classic-gold",
    name: "Classic Gold Executive",
    description: "Traditional elegant certificate layout with gold borders, formal typography, and signature fields.",
    layout: {
      width: 1000,
      height: 700,
      backgroundColor: "#FFFFFF",
      borderColor: "#D97706",
      borderWidth: 10,
      showFrame: true,
      frameStyle: "classic",
      elements: [
        {
          id: "el-title",
          type: "title",
          label: "Certificate Title",
          text: "CERTIFICATE OF ACHIEVEMENT",
          x: 50,
          y: 18,
          fontSize: 32,
          fontFamily: "Cinzel, Times New Roman, serif",
          fontStyle: "bold",
          color: "#0F172A",
          align: "center",
          visible: true,
          zIndex: 1,
        },
        {
          id: "el-subtitle",
          type: "subtitle",
          label: "Certificate Label",
          text: "PROUDLY PRESENTED TO",
          x: 50,
          y: 28,
          fontSize: 14,
          fontFamily: "Inter, sans-serif",
          fontStyle: "bold",
          color: "#D97706",
          align: "center",
          visible: true,
          zIndex: 2,
        },
        {
          id: "el-name",
          type: "name",
          label: "Participant Name",
          text: "{{name}}",
          x: 50,
          y: 40,
          fontSize: 42,
          fontFamily: "Playfair Display, Georgia, serif",
          fontStyle: "bold",
          color: "#1E3A8A",
          align: "center",
          visible: true,
          zIndex: 3,
        },
        {
          id: "el-customText",
          type: "customText",
          label: "Custom Description",
          text: "For outstanding performance, dedication, and technical excellence in",
          x: 50,
          y: 52,
          fontSize: 16,
          fontFamily: "Inter, sans-serif",
          fontStyle: "normal",
          color: "#475569",
          align: "center",
          visible: true,
          zIndex: 4,
        },
        {
          id: "el-eventName",
          type: "eventName",
          label: "Event Name",
          text: "{{eventName}}",
          x: 50,
          y: 60,
          fontSize: 22,
          fontFamily: "Inter, sans-serif",
          fontStyle: "bold",
          color: "#2563EB",
          align: "center",
          visible: true,
          zIndex: 5,
        },
        {
          id: "el-date",
          type: "date",
          label: "Issue Date",
          text: "Issued on: {{date}}",
          x: 25,
          y: 80,
          fontSize: 14,
          fontFamily: "Inter, sans-serif",
          fontStyle: "normal",
          color: "#64748B",
          align: "center",
          visible: true,
          zIndex: 6,
        },
        {
          id: "el-uniqueId",
          type: "uniqueId",
          label: "Verification ID",
          text: "ID: {{uniqueId}}",
          x: 25,
          y: 86,
          fontSize: 13,
          fontFamily: "Courier New, monospace",
          fontStyle: "bold",
          color: "#2563EB",
          align: "center",
          visible: true,
          zIndex: 7,
        },
        {
          id: "el-qrCode",
          type: "qrCode",
          label: "QR Code",
          text: "",
          x: 78,
          y: 75,
          fontSize: 14,
          fontFamily: "Inter",
          color: "#0F172A",
          align: "center",
          width: 90,
          height: 90,
          visible: true,
          zIndex: 8,
        },
      ],
    },
  },
  {
    id: "cyberpunk-dark",
    name: "Cyberpunk Arena Dark",
    description: "Sleek dark theme with neon cyan and pink accents tailored for developer hackathons.",
    layout: {
      width: 1000,
      height: 700,
      backgroundColor: "#0F172A",
      borderColor: "#06B6D4",
      borderWidth: 8,
      showFrame: true,
      frameStyle: "dark",
      elements: [
        {
          id: "el-title",
          type: "title",
          label: "Certificate Title",
          text: "FRONTEND ARENA CERTIFICATE",
          x: 50,
          y: 18,
          fontSize: 30,
          fontFamily: "Outfit, Inter, sans-serif",
          fontStyle: "bold",
          color: "#06B6D4",
          align: "center",
          visible: true,
          zIndex: 1,
        },
        {
          id: "el-subtitle",
          type: "subtitle",
          label: "Certificate Label",
          text: "OFFICIAL PARTICIPATION & ACHIEVEMENT CREDENTIAL",
          x: 50,
          y: 27,
          fontSize: 12,
          fontFamily: "Inter, sans-serif",
          fontStyle: "bold",
          color: "#2563EB",
          align: "center",
          visible: true,
          zIndex: 2,
        },
        {
          id: "el-name",
          type: "name",
          label: "Participant Name",
          text: "{{name}}",
          x: 50,
          y: 40,
          fontSize: 42,
          fontFamily: "Outfit, sans-serif",
          fontStyle: "bold",
          color: "#FFFFFF",
          align: "center",
          visible: true,
          zIndex: 3,
        },
        {
          id: "el-customText",
          type: "customText",
          label: "Custom Description",
          text: "Has successfully submitted code and completed automated judging for",
          x: 50,
          y: 52,
          fontSize: 15,
          fontFamily: "Inter, sans-serif",
          fontStyle: "normal",
          color: "#94A3B8",
          align: "center",
          visible: true,
          zIndex: 4,
        },
        {
          id: "el-eventName",
          type: "eventName",
          label: "Event Name",
          text: "{{eventName}}",
          x: 50,
          y: 60,
          fontSize: 22,
          fontFamily: "Outfit, sans-serif",
          fontStyle: "bold",
          color: "#38BDF8",
          align: "center",
          visible: true,
          zIndex: 5,
        },
        {
          id: "el-uniqueId",
          type: "uniqueId",
          label: "Verification ID",
          text: "ID: {{uniqueId}}",
          x: 25,
          y: 82,
          fontSize: 14,
          fontFamily: "Courier New, monospace",
          fontStyle: "bold",
          color: "#06B6D4",
          align: "center",
          visible: true,
          zIndex: 6,
        },
        {
          id: "el-date",
          type: "date",
          label: "Issue Date",
          text: "Issued on: {{date}}",
          x: 25,
          y: 88,
          fontSize: 12,
          fontFamily: "Inter, sans-serif",
          fontStyle: "normal",
          color: "#94A3B8",
          align: "center",
          visible: true,
          zIndex: 7,
        },
        {
          id: "el-qrCode",
          type: "qrCode",
          label: "QR Code",
          text: "",
          x: 80,
          y: 74,
          fontSize: 14,
          fontFamily: "Inter",
          color: "#FFFFFF",
          align: "center",
          width: 90,
          height: 90,
          visible: true,
          zIndex: 8,
        },
      ],
    },
  },
];
